### ISSUE TITLE
Cannot build, because of libbz3

### ISSUE THREAD

**Issue by lukypko** [pete4abw/lrzip-next#103]
### lrzip-next Version

lzma-22.01, b6e1f843a442fe2c3af76d30285398116d444a60

### lrzip-next command line

just a build

### What happened?

Just build it:
~~~
mkdir new_dir
cd new_dir
git clone https://github.com/pete4abw/lrzip-next
cd lrzip-next
./autogen.sh
./configure
make
~~~

Crashed on:
~~~
Making all in src
make[2]: Entering directory '/home/luky/temp/lrzip2/lrzipbz3_latest/lrzip-next/src'
depbase=`echo stream.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
/bin/bash ../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I..    -I . -I .. -I ../src/include -I ../src/lzma/include -g -O2  -MT stream.lo -MD -MP -MF $depbase.Tpo -c -o stream.lo stream.c &&\
mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -I . -I .. -I ../src/include -I ../src/lzma/include -g -O2 -MT stream.lo -MD -MP -MF .deps/stream.Tpo -c stream.c  -fPIC -DPIC -o .libs/stream.o
stream.c:46:10: fatal error: libbz3.h: No such file or directory
   46 | #include <libbz3.h>
      |          ^~~~~~~~~~
compilation terminated.
make[2]: *** [Makefile:566: stream.lo] Error 1
make[2]: Leaving directory '/home/luky/temp/lrzip2/lrzipbz3_latest/lrzip-next/src'
make[1]: *** [Makefile:502: all-recursive] Error 1
make[1]: Leaving directory '/home/luky/temp/lrzip2/lrzipbz3_latest/lrzip-next'
make: *** [Makefile:413: all] Error 2
~~~

To fix it, in `stream.c` in line 45 change:
~~~
#include <libbz3.h>
~~~
to
~~~
#include <lib/libbz3/libbz3.h>
~~~

It was just a quick fix, but I guess it is not the right way how to fix it (**make** file configuration is difficult for me)

### What was expected behavior?

build

### Steps to reproduce

lazy

### Please provide system details

cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=21.04
DISTRIB_CODENAME=hirsute
DISTRIB_DESCRIPTION="Ubuntu 21.04"

I know it is already dead, but I'm lazy to upgrade

uname -a
Linux lukynb 5.11.0-49-generic #55-Ubuntu SMP Wed Jan 12 17:36:34 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

gcc --version
gcc (Ubuntu 10.3.0-1ubuntu1) 10.3.0
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

ld --version
GNU ld (GNU Binutils for Ubuntu) 2.36.1
Copyright (C) 2021 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or (at your option) a later version.
This program has absolutely no warranty.

**Comment by pete4abw** [comment]
Thank you for the report. Indeed, if bzip3 was not installed on the host, the include directive for `libbz3.h` would fail. bzip3 should not be a requirement. The library is included with `lrzip-next` source. Both **lzma-22.01** and **whats-next** branches fixed.
