### ISSUE TITLE
Found typo in viewing compression info on a lrz file

### ISSUE THREAD

**Issue by Merculous** [pete4abw/lrzip-next#124]
I used lrzip-next -vvi to view compression results, this line here happened to contain a typo. I would do a pr but I'm too lazy.

https://github.com/pete4abw/lrzip-next/blob/9a7c1b84cae9c1025ddd329608d67ee971515d3c/src/lrzip.c#L1353

**Comment by pete4abw** [comment]
No PR needed...Fixing...
