### ISSUE TITLE
:bulb: possible precomp support

### ISSUE THREAD

**Issue by Merculous** [pete4abw/lrzip-next#136]
### lrzip-next Version

N/A

### Feature Suggestion

This fork is vastly better than the original.

https://github.com/nicolas-comerci/precomp-cpp

The maintainer of this fork has greatly updated this program, and especially has worked on making it more reliable and best of all, work with stdin/stdout.

I'm not 100% sure how this would be integrated, but sometimes this fork (lrzip-next) does provide good compression.

If stability is good enough, and granted that if precomp was added, (as of now, recent additions to verifying integrity are still being worked on to be faster, the current code is slightly slower [ask the fork author about statistics]) if the user isn't really worried about compression duration, I think this would give lrzip-next even more compression than imaginable.

I think the actual aspect of how precomp works is very useful, however it may take a bit longer since precomp itself puts already compressed files into formats which can achieve better compression, the whole point of precomp is to format data for another program to make use of the larger context, which should enable compressing data even more, instead of making use of the original data.

I have no idea if its ready to be added soon, but it would be awesome to see a implementation that actually makes use of this program.

**Comment by pete4abw** [comment]
@Merculous , thank you for this suggestion. `lrzip-next` does not produce files that are readable by other applications. It appears this program is a repackager -- where it unpacks a compressed file, processes it, and then repacks it in the original format. Then, you must use the program to unpack the packed compressed file again. It would not be able to read or write an `lrz` file. We ditched the library code years ago. So there is no API to follow. `lrzip/lrzip-next` already has an excellent stream pre-processor. It uses  `rzip`. Replacing the stream pre-processor would be a BIG BIG project.

I will leave this issue open for a bit in case anyone else cares to comment. If you ran benchmarks or have some use cases you want to present, please provide.

**Comment by pete4abw** [comment]
No other comments, so closing for now. This really is not feasible. Thank you @Merculous for the suggestion.
