### ISSUE TITLE
:lady_beetle: fake_mremap does not compile

### ISSUE THREAD

**Issue by asdfugil** [pete4abw/lrzip-next#151]
### lrzip-next Version

lrzip-next version 0.12.4-2-b6340c0

### lrzip-next command line

...

### What happened?

Does not compile: 
```
rzip.c:779:3: error: use of undeclared identifier 'control'
                fatal("fake_mremap: This should only be used to shrink things. I'm not bothering with this.\n");
                ^
../src/include/util.h:46:26: note: expanded from macro 'fatal'
#define fatal(...) fatal(control, __LINE__, __FILE__, __func__, __VA_ARGS__)
```

the fatal macro uses the control variable, but the control variable is not defined in the context of fake_mremap

### What was expected behavior?

It compiles

### Steps to reproduce

1. Be on any system that is not Linux
2. ./configure
3. make

### Please provide system details

OS Distro: macOS
Kernel Version (uname -a): 23.2.0
System ram (free -h): 16 GiB

### Additional Context
changing the fatal to something like abort works around the problem

**Comment by pete4abw** [comment]
That's an oops on my part. Original code just had a `fprintf` to stderr and an `exit(1)`. i changed it to a `fatal()` macro but did not realize that the control structure was absent. It was not meant to be in this function. Since I do not compile on MAC, this never happened on my system! To get around it for now, just comment out the fatal line and add `exit(1);` The original was like this:
```
	if (new_size > old_size) {
		fprintf(stderr, "fake_mremap: This should only be used to shrink things. I'm not bothering with this.\n");
		exit(1);
```

**Comment by asdfugil** [comment]
alternatively, modify the fake_mremap function to take a control argument, and use a marco to pass it in:

```c
# define mremap(a, b, c, d) fake_mremap(control, a, b, c, d);

static inline void *fake_mremap(rzip_control *control, void *old_address, size_t old_size, size_t new_size, int flags __UNUSED__)
{
        if (new_size > old_size)
                fatal("fake_mremap: This should only be used to shrink things. I'm not bothering with this.\n");
        else {
                /* new_size occupies N pages; old_size occupies M > N pages;
                 we want to unmap the M - N pages at the end.
                 note the idiom: ceiling(n/k) = (n+k-1) div k */
                size_t kept_n = (new_size + PAGE_SIZE - 1) / PAGE_SIZE;
                int ret = munmap(old_address + (kept_n * PAGE_SIZE), old_size - (kept_n * PAGE_SIZE));

                if (ret < 0)
                        return MAP_FAILED;

                return old_address;
        }
}
```

**Comment by pete4abw** [comment]
Fix proposed in branch whats-next. Please review and comment.
