### ISSUE TITLE
libzpaq detects macOS as Windows

### ISSUE THREAD

**Issue by SMillerDev** [pete4abw/lrzip-next#17]
It seems that the `#ifdef` in libzpaq.cpp is not extensive enough to work on macOS compilers. 

[libzpaq.cpp#L31](https://github.com/pete4abw/lrzip-next/blob/HEAD/src/lib/libzpaq/libzpaq.cpp#L31) has the `#ifdef` and here is an article I found about the issue: [http://nadeausoftware.com/articles/2012/01/c_c_tip_how_use_compiler_predefined_macros_detect_operating_system#UNIX](http://web.archive.org/web/20160306052035/http://nadeausoftware.com/articles/2012/01/c_c_tip_how_use_compiler_predefined_macros_detect_operating_system#UNIX)

---

After resolving this, `make` still fails with the following error:
```console
/bin/sh ../../../libtool  --tag=CXX   --mode=compile clang++ -DHAVE_CONFIG_H -I. -I../../..     -g -O2  -O3 -c -o libzpaq.lo libzpaq.cpp
libtool: compile:  clang++ -DHAVE_CONFIG_H -I. -I../../.. -g -O2 -O3 -c libzpaq.cpp  -fno-common -DPIC -o .libs/libzpaq.o
libzpaq.cpp:87:25: error: use of undeclared identifier 'MEM_RELEASE'
      VirtualFree(p, 0, MEM_RELEASE);
                        ^
libzpaq.cpp:98:37: error: use of undeclared identifier 'MEM_RESERVE'
    p=(U8*)VirtualAlloc(0, newsize, MEM_RESERVE|MEM_COMMIT,
                                    ^
libzpaq.cpp:98:49: error: use of undeclared identifier 'MEM_COMMIT'
    p=(U8*)VirtualAlloc(0, newsize, MEM_RESERVE|MEM_COMMIT,
                                                ^
libzpaq.cpp:99:25: error: use of undeclared identifier 'PAGE_EXECUTE_READWRITE'
                        PAGE_EXECUTE_READWRITE);
                        ^
4 errors generated.
make[2]: *** [libzpaq.lo] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```

**Comment by pete4abw** [comment]
Thank you for the report. In the [ZPAQ Readme](https://github.com/pete4abw/lrzip-next/blob/master/src/lib/libzpaq/doc/readme.txt), it has a suggestion.

`g++ -O3 -march=native -Dunix zpaq.cpp libzpaq.cpp -pthread -o zpaq`

To compile for non x86 or x86-64 hardware use option -DNOJIT
Some compilers complain about "-march=native" option. If so, take it out.

May I ask you traverse directly to the src/lib/libzpaq directory and try to compile directly using g++?
(This won't build the needed library, but it may help pin down how to tailor the Makefile or header files for zpaq and MacOS.)

This is a newer version of zpaq, so it's possible there is an inconsistency. Can you say if this compiled in 0.641? IIRC lzma files are built before zpaq.

Thank you again for this report. I hope we can get this to build for MacOS.

**Comment by SMillerDev** [comment]
I'm just following the build instructions in the Readme so I don't really know how to modify the build arguments.

As for traversing into the directory, could you post the commands you want me to run? I'm sufficient at running makefiles and reading errors but I wouldn't know how to run `g++` manually.

**Comment by pete4abw** [comment]
I'm sorry if I was not clear. Change dir to the lrzip-next clone directory and then
```
$ cd src/lib/libzpaq
$ make clean
$ g++ -O3 -march=native -M -Dunix libzpaq.cpp -pthread -o libzpaq
```
I just want to see if compile goes through. If not, we can try and modify some #ifdef statements. I added a compiletime option, **-M** so copy and paste.

**Comment by SMillerDev** [comment]
Seems to be fine.
```
bash-3.2$ cd src/lib/libzpaq
bash-3.2$ make clean
rm -rf .libs _libs
test -z "libzpaq.la" || rm -f libzpaq.la
rm -f *.o
rm -f *.lo
rm -f ./so_locations
bash-3.2$ g++ -O3 -march=native -M -Dunix libzpaq.cpp -pthread -o libzpaq
clang: warning: -Wl,-headerpad_max_install_names: 'linker' input unused [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-L/usr/local/lib' [-Wunused-command-line-argument]
```

**Comment by pete4abw** [comment]
That's good news. Now, can you please zip the following files and upload to this issue.
All under the lrzip-next clone directory.

1. config.h
2. config.log
3. config.status
2. Makefile
3. src/lib/libzpaq/Makefile

I'll take a look and see what might be changed and double check the link you had shared earlier. Thank you for helping to debug this. It may take me a couple of days to revert.

**Comment by SMillerDev** [comment]
I just zipped up the entire git directory in the state after running a failing `make`. Since I used homebrew to build lrzip (and now lrzip-next) the entire thing is build in a `/tmp` directory anyway.

[lrzip-next-state.zip](https://github.com/pete4abw/lrzip-next/files/6206013/lrzip-next-state.zip)

**Comment by pete4abw** [comment]
I'll review. Unfortunately, I don't have a Mac rig, so I may have more things for you to try. ITMT, I would like you to download the ZPAQ source from: [ZPAQ Download](http://mattmahoney.net/dc/zpaq715.zip), unzip it, and just type `make`.

Mahoney's Makefile is simple and could help set this up for `lrzip-next`. Thank you again.

ZPAQ Makefile Compile Defaults
```
CXX=g++
CPPFLAGS+=-Dunix
# CPPFLAGS+=NOJIT
CXXFLAGS=-O3 -march=native
```

**Comment by pete4abw** [comment]
Would you please try cloning this new branch and let me know. Thank you.
`git clone https://github.com/pete4abw/lrzip-next -b zpaq-mac`

A simple one line change to define `unix` on compile line.
```
diff --git a/src/lib/libzpaq/Makefile.am b/src/lib/libzpaq/Makefile.am
index d493fca..6784fbb 100644
--- a/src/lib/libzpaq/Makefile.am
+++ b/src/lib/libzpaq/Makefile.am
@@ -1,7 +1,8 @@
 MAINTAINERCLEANFILES = Makefile.in
 
 ## zpaq recommends best optimization for speed
-CXXFLAGS += -O3
+## define unix for Apple and Linux
+CXXFLAGS += -O3 -Dunix
 
 noinst_LTLIBRARIES = libzpaq.la
 libzpaq_la_SOURCES = \
```

**Comment by SMillerDev** [comment]
`libzpaq` is fixed on that branch, the error is now:

```console
libtool: compile:  clang -DHAVE_CONFIG_H -I. -I.. -I . -I .. -I ../src/include -I ../src/lzma/include -DNDEBUG -g -O2 -pthread -c aes.c  -fno-common -DPIC -o .libs/aes.o
lrzip.c:78:35: error: expected ';' after top level declarator
i64 get_ram(rzip_control *control)
                                  ^
                                  ;
lrzip.c:81:1: error: expected identifier or '('
{
^
2 errors generated.
make[2]: *** [lrzip.lo] Error 1
make[2]: *** Waiting for unfinished jobs....
```

**Comment by pete4abw** [comment]
Wow, this code has not changed in years and years. Maybe no one on MAC used lrzip? Could you please do this (rather than poke a new branch). edit src/lrzip.c as follows

line 80
```
78 i64 get_ram(rzip_control *control)
79 #ifdef __APPLE__
80 # include <sys/sysctl.h>
```
Try removing the space between **#** and **include** and in the top directory of lrzip-next, type

`$ lrzip-next: make`

We're getting there!

**Comment by SMillerDev** [comment]
That did not change anything

```console
libtool: compile:  clang -DHAVE_CONFIG_H -I. -I.. -I . -I .. -I ../src/include -I ../src/lzma/include -DNDEBUG -g -O2 -pthread -c stream.c  -fno-common -DPIC -o .libs/stream.o
lrzip.c:78:35: error: expected ';' after top level declarator
i64 get_ram(rzip_control *control)
                                  ^
                                  ;
lrzip.c:81:1: error: expected identifier or '('
{
^
2 errors generated.
make[2]: *** [lrzip.lo] Error 1
make[2]: *** Waiting for unfinished jobs....
```

**Comment by pete4abw** [comment]
Well, next, let's try and adjust the braces.

patch lrzip.c with the below, or edit manually for braces.

Add a curly brace under `i64 get_ram`
Remove curly brace under `#include <sys/sysctl.h>`
Remove curly brace under `#else`

save and try `make` again.
```
diff --git a/src/lrzip.c b/src/lrzip.c
index 399ed01..3408b17 100644
--- a/src/lrzip.c
+++ b/src/lrzip.c
@@ -76,9 +76,9 @@ static i64 fdout_seekto(rzip_control *control, i64 pos)
 }
 
 i64 get_ram(rzip_control *control)
+{
 #ifdef __APPLE__
 # include <sys/sysctl.h>
-{
        int mib[2];
        size_t len;
        i64 ramsize;
@@ -87,7 +87,6 @@ i64 get_ram(rzip_control *control)
        mib[1] = HW_MEMSIZE;
        sysctl(mib, 2, &ramsize, &len, NULL, 0);
 #else /* __APPLE__ */
-{
        i64 ramsize;
        FILE *meminfo;
        char aux[256];
```

I appreciate all the time you are taking to test!

**Comment by SMillerDev** [comment]
Yes, that was it for the bracket issue. Next up 😅 
```console
libtool: link: ( cd ".libs" && rm -f "liblrzip-next.la" && ln -s "../liblrzip-next.la" "liblrzip-next.la" )
Making all in src/demo
clang -DHAVE_CONFIG_H -I. -I../..     -g -O2 -pthread -c -o decompress_demo.o decompress_demo.c
clang -DHAVE_CONFIG_H -I. -I../..     -g -O2 -pthread -c -o liblrzip_demo.o liblrzip_demo.c
decompress_demo.c:26:10: fatal error: 'Lrzip.h' file not found
#include <Lrzip.h>
         ^~~~~~~~~
1 error generated.
liblrzip_demo.c:37:10: fatal error: 'Lrzip.h' file not found
#include <Lrzip.h>
         ^~~~~~~~~
make[2]: *** [decompress_demo.o] Error 1
make[2]: *** Waiting for unfinished jobs....
1 error generated.
```

I appreciate the effort in helping me debug too!

**Comment by pete4abw** [comment]
There's no reason to compile the demo files. This will fail because it (incorrectly) assumes that `Lrzip.h` has already been installed in /usr/include. Of course, this would not happen on an initial install.

I appreciate all your help on this and am sorry this is so painful! However, try cloning master again and let's see if we get further!

**Comment by SMillerDev** [comment]
Master now builds as expected 👍

**Comment by pete4abw** [comment]
Thank you for exposing these defects. I am glad we could use it. I hope you enjoy `lrzip-next` (of course you can rename the executable if you like). It has many neat new features worth exploring. I value any comments or suggestions you may have as you explore lrzip-next. And, of course, bug reports are important and welcome!
