### ISSUE TITLE
Any plans to release a pre-compiled binary?

### ISSUE THREAD

**Issue by 8465231** [pete4abw/lrzip-next#18]
You were helping me in the main LRzip repo.

I found this when looking at your account and it looks real interesting.

Any plans to release a pre-compiled version (or even better a dockertized version combined with lrzip-fee)? 

I have no idea where to start for compiling, have not done it in years and then was a clear case of failing a few dozen times and not having a clue why it finally worked, then deciding it was just not worth the hassle lol.

Would this version net me any real world gains in compression / speed for my 2.5TB file using lmza compression?

lrzip-fe also looks FANTASTIC! While I will happily run scripts and such from CLI, give me a GUI for anything that I don't do repeatedly any day of the week.

Thanks for the help BTW. I love learning.

**Comment by pete4abw** [comment]
No no plans for pre-compiled. `configure, make, make install` are not beyond most. Docker? I don't see the need yet. Back to your original issue, I strongly recommend using 
`tar -I 'lrzip [options] -cf file.tar.lrz files...` 
or pipe tar to lrzip, 
`tar -cf - files... | lrzip [options]  -o file.tar.lrz`

Why you would waste time tar'ring a huge file, basically doubling your disk use, is unclear. When you use `tar` and lrz you can actually select which files/directories to extract. If you did the tarfile lrzip file route, you would have to extract your huge 2.5TB file and then selectively extract.

I recommend reading through some of the READMEs, Benchmarks, the [Wiki](https://github.com/pete4abw/lrzip-next/wiki) here and [Discussions](https://github.com/pete4abw/lrzip-next/discussions). Then do small scale tests to see about benefits.

This [README](https://github.com/pete4abw/lrzip-next/blob/master/doc/README.NEW.BENCHMARK.ALGO.md) in the doc directory is helpful in selecting the best compression.

Good luck and thank you for your interest.

**Comment by 8465231** [comment]
You greatly overestimate the abilities of linux noobs. lol

First issue, don't have git installed or know how to use it. I figured that out after some googling though. 

Hint, this is basically the issues I always have with linux, no matter what I want to do I always seem to be missing the right package or dependency and can never seem to find the right names to install it. Leading to an endless google loop just to use one program.

With docker I run 1 command that has everything all setup and ready to go in seconds regardless of skill level. Docker is the single reason I have even ventured back into linux (well, that and unraid). Off topic but I know it is easy to forget what it is like not even knowing what to search for to find the answer you want.

Just to give you an idea what a noob goes through for a "simple" command like this here is what I spent the last 45 minutes doing:

Second issue:

/github/lrzip-next# ./autogen.sh
Running autoreconf -if...
./autogen.sh: 8: autoreconf: not found

back to google...

Fixed that by installing autoreconf but then ran into this problem:

Running autoreconf -if...
./util/gitdesc.sh: 50: Bad substitution
./util/gitdesc.sh: 50: Bad substitution
./util/gitdesc.sh: 50: Bad substitution
........
./util/gitdesc.sh: 50: Bad substitution
./util/gitdesc.sh: 50: Bad substitution
configure.ac:20: error: possibly undefined macro: AC_PROG_LIBTOOL
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /usr/bin/autoconf failed with exit status: 1

Google is not being helpful with this one, m4_pattern_allow is not helping. It looks like AC_PROG_LIBTOOL is a package but apt install just says:

E: Unable to locate package AC_PROG_LIBTOOL

After a lot of searching I found an indirect answer that said I need to install libtool, this at least made a difference but still spit out a ton of errors.

Thankfully the script spit out this with the next error:

configure: error: Could not find zlib library - please install zlib-dev

Sadly this did not work and gave this error: E: Unable to locate package zlib-dev

So back to google I went, more searching with no real answers finally led to finding the correct name for the package was zlib1g-dev

Next error is configure: error: Could not find bz2 library - please install libbz2-dev

Thankfully this one was correct but still a ton of errors and a new error:

WARNING:
The doxygen program was not found in your execute path.
You may have doxygen installed somewhere not covered by your path.

If this is the case make sure you have the packages installed, AND
that the doxygen program is in your execute path (see your
shell manual page on setting the $PATH environment variable), OR
alternatively, specify the program to use with --with-doxygen.
configure: WARNING: no doxygen detected. Documentation will not be built
checking that generated files are newer than configure... done

Back to google I go. Install doxygen and try again.

Next error, this one much harder to figure out, I am sure something is missing but no hints on what it could be.

config.status: error: Something went wrong bootstrapping makefile fragments
    for automatic dependency tracking.  Try re-running configure with the
    '--disable-dependency-tracking' option to at least be able to build
    the package (albeit without support for automatic dependency tracking).
See `config.log' for more details

config.log is useless to me.

I am also not finding much help on google. Others had the issue but it seemed to be the wrong version of a package not a missing package. 

I start installing every package I see mentioned but it is not helping. Still gets the same error.

After 45 minutes, I am going to have to take a break. lol

FYI, this is not aimed at you, more just a rant about trying to do things on linux in a general sense. This is my linux life pretty much, I spend more time on google then doing anything on linux until I discovered docker and the skies opened, I could actually run programs without wanting to throw the computer at the wall! lol

I am going to read those links you posted now, thanks for those, I was not even aware that github had a discussion section, this should of been posted there I am sure.

Sorry for posting this in the wrong place. I am used to discussion forums.

**Comment by pete4abw** [comment]
I feel your pain.  But As the Readme says, you must clone the repo in order to compile. Downloading a tarball will not build. There's a reason for this since the version is dependant on specific commits and if something breaks it's helpful to know the precise version built.


 If you're going to build your own package, you need most of not all development libraries. Normally this is an installation option. Since lrzip-next is not offered as a package by distros, evaluators must build and install by themselves.

My advice to you is install the development packages for Ubuntu. Git will be included.

Discussions are on the top level menu. Better place for this. I'm moving this over...

Regards
