### ISSUE TITLE
:lady_beetle: [Outputted text during decompression of a ZPAQ compressed file overlaps other text]

### ISSUE THREAD

**Issue by Merculous** [pete4abw/lrzip-next#53]
### lrzip-next Version

lrzip version 0.8.8

### lrzip-next command line

lrzip -U -T -z -p 1 -L 9 -vv

### What happened?

NOTE: lrzip-next is symlinked as lrzip.

When I decompress any ZPAQ compressed file I get...

`Validating file for consZPAQncy.1:30%  pressing...`

The main issue is easily spotted.  As for below, "ZPAQ: ..%" will appear in the middle or somewhere between the 1: ..% 2: ..%, and etc.

There's another issue that's related to this, except it happens when decompressing with multiple threads. I had a file that'll show this, however I deleted it as I'm reworking the file. Once I have the text showing this issue, I will add it here, so please don't close. I will try to get that bit added asap. I assume its reproducible? My file was relatively big, however the original data was 50GB+ so it happens when using max amount of threads basically.

### What was expected behavior?

ZPAQ text should be on the right side of the validation text, or below.

### Steps to reproduce

I usually see this with ZPAQ only, I have not gotten this issue with LZMA (I have not used any other algorithm).

### Please provide system details

OS Distro:
Ubuntu (Server)

Kernel Version (uname -a):
Linux server 5.4.0-91-generic #102-Ubuntu SMP Fri Nov 5 16:31:28 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

System ram (free -h): 8GB RAM, 4GB Swap (zram not configured)

**Comment by pete4abw** [comment]
Thanks for the report.

`-vv` output is messy and at some point will need to be either redone or eliminated.
I created a print_progress flag that is used to determine whether a newline is needed in places.
Normally this works fine when `lrzip-next` is merrily counting up percentages. ZPAQ progress is
shown differently as you know. Percent by thread in multiples of 10.

It looks different and uglier depending if you use -v or -vv or neither.

**-vv**
```
Validating file for consistency...
Detected lrzip version 0.8 file.
Decompressing...
Reading chunk_bytes at 18
```

**-v**
```
Validating file for consistency...
Detected lrzip version 0.8 file.
100%      95.37 /     95.37 MB  1:100%  2:100%  3:100%  4:100%  5:100%  6:100%  7:100%  8:100%  9:100%  10:100%  
Average DeCompression Speed: 19.000MB/s
```
where until the end, ZPAQ compression is shown nicely.

**no verbosity**
``
Output filename is: enwik8
100%      95.37 /     95.37 MBy.1:100%  2:100%  3:100%  4:100%  5:100%  6:100%  7:100%  8:100%  9:100%  10:100%  
Average DeCompression Speed: 19.000MB/s
``
where the validating message gets overwritten at the end.

There is no immediate fix other than to take out the ZPAQ decompression percentages. The file validation is something I put in as an extra check to make sure a file is valid.

An immediate fix is to change the way the Validating message is displayed changing print_progress to print_output and see.
```
1554         // vailidate file on decompression or test
1555         if (STDIN)
1556                 print_err("Unable to validate a file from STDIN. To validate, check file directly.");
1557         else {
1558                 print_progress("Validating file for consistency...");
1559                 if (unlikely((get_fileinfo(control)) == false))
1560                         failure_return(("File validation failed. Corrupt lrzip archive. Cannot continue\n"),false);
1561         }
1562         print_progress("Decompressing...");
```

Thanks for the report.

Peter

**Comment by pete4abw** [comment]
Sorry for late reply. Was away. I created a define macro called **print_progress** which uses a flag variable to determine whether or not a newline is needed. You can see it `lrzip_private.h` for more info. It's possible maybe with zpaq to not use it so newlines will print. But then the zpaq display will still be broken. The whole zpaq thing was intended to show some progress from within the zpaq compression run. Unlike lzma, as you know, zpaq can really take a long time to return. I'm keeping this open, but zpaq has other issues like not being able to show compression progress anymore. Thank you again

**Comment by pete4abw** [comment]
@Merculous , I had a chance to look at this and there were a few issues, depending on verbosity. Would you please test this patch and let me know if it improves output flow?

Please try
`lrzip-next -Pt file.lrz`
`lrzip-next -vt file.lrz`
`lrzip-next -vv file.lrz`

I use `-t` so nothing gets overwritten.

If good, I'll push the patch, Thank you again.
[fix_zpaqd.patch.gz](https://github.com/pete4abw/lrzip-next/files/7788644/fix_zpaqd.patch.gz)

**Comment by pete4abw** [comment]
Fixed. Thank you. Ignore prior patch.
