### ISSUE TITLE
:bulb: "Split" archive support.

### ISSUE THREAD

**Issue by ghost** [pete4abw/lrzip-next#73]
### lrzip-next Version

lrzip version 0.8.8-3-9f2257d

### Feature Suggestion

[(I have proposed it on ZPAQ forums and got rejected.)](https://encode.su/threads/456-zpaq-updates?p=70992&viewfull=1#post70992)

After deduplication and before compression, instead of outputting a single file, it outputs a "metadata-only" file (`data.lrz.m`) and a directory (`data.lrz.d`) of blocks (with the filenames describing the block number and state (compressed/uncompressed/incompressible), like `0-12345_Uncompressed.dat`).
When needed, do a stream compression of each block and delete the uncompressed ones.
This is similar to RAR volumes but the block size is not fixed and incompressible data is taken care of.

The reason:

On large (more than a few gibibytes) datasets, compression would take a long time to complete (especially when using ZPAQ). Currently, it is nearly impossible to pause or resume this process, let alone keeping it running between reboots.
With this, after deduplication and filtering, you can just compress the blocks separately. If you have to reboot, only the blocks that are currently compressing have to be restarted, instead of the whole dataset.
Also, since the blocks are standalone, you can compress them on different locations and different computers, with different methods, and making storage and backups easier.

An example:

To compress:

    $ lrzip-next --split-archive -n -o ./output/data.lrz.m ./data
    $ lrzip-next --split-archive --lzma ./output/data.lrz.m
(The second command should ignore missing blocks since they may be elsewhere.)

To extract:

    $ lrzip-next --split-archive -d -o ./data ./output/data.lrz.m

### Please provide system details

OS Distro: Debian Sid
Kernel Version (uname -a): `Linux localhost 5.17.3 #6 SMP PREEMPT Tue Apr 19 00:23:50 +08 2022 x86_64 GNU/Linux`
System ram (free -h): 
```
               total        used        free      shared  buff/cache   available
Mem:           125Gi       1.5Gi       122Gi       7.1Mi       1.2Gi       123Gi
Swap:             0B          0B          0B
```

**Comment by pete4abw** [comment]
The rzip pre-processing phase scans only a chunk at a time. For example, when I archive a virtual machine of 75G, it takes 8 passes to compress the whole file.Each pass becomes a chunk (as `lrzip-next` sees it) and each chunk is compressed as  a series of blocks and is a subset of the whole file. So what you are suggesting is not possible.

However, if what you are suggesting is compress a chunk at a time, i.e. compress chunks 1-3 only, or 4-6 only, while possible, would be very messy since the file would have to pieced back together again on decompression.

A different approach would be to use a program like `dd` to pass only so many bytes to `lrzip-next`. Using a combination of block size and count, and or skip, you can approximate your desire.

```
$ dd if=enwik9 bs=1M count=100 | lrzip-next -fo partofenwik9.lrz -L1  -
Using configuration file /home/peter/.lrzip/lrzip.conf
The following options are in effect for this COMPRESSION.
Threading is ENABLED. Number of CPUs detected: 8
Detected 16,558,112,768 bytes ram
Nice Value: 19
Show Progress
Verbose
Overwrite Files
Output Filename Specified: partofenwik9.lrz
Temporary Directory set as: ./
Compression mode is: LZMA. LZ4 Compressibility testing enabled
Compression level 1
RZIP Compression level 1
Initial LZMA Dictionary Size: 262,144
SHA256 Hashing Used
Heuristically Computed Compression Window: 52 = 5,200MB
100+0 records in
100+0 records out
104857600 bytes (105 MB, 100 MiB) copied, 0.0590955 s, 1.8 GB/s
Per Thread Memory Overhead is 9,322,496
Beginning rzip pre-processing phase
Compression Ratio: 3.036. bpb: 2.635. Average Compression Speed: 33.333MB/s.
Total time: 00:00:02.48
```

I'll leave this open

**Comment by pete4abw** [comment]
I think the `dd` command would achieve what you seek. The risk is that changes occur to the file you are archiving mid-way.
