### ISSUE TITLE
autogen.sh    #!/bin.env bash    cannot find bash (maybe problem on my system but bash is there (following the .sh in utils same problem

### ISSUE THREAD

**Issue by chargen** [pete4abw/lrzip-next#76]
### lrzip-next Version

latest of 20220509

### lrzip-next command line

autogen.sh

### What happened?

autogen.sh    #!/bin.env bash    cannot find bash (maybe problem on my system but bash is there (following the .sh in utils same problem

### What was expected behavior?

to run

### Steps to reproduce

as shown

### Please provide system details

OS Distro: WSL
Kernel Version (uname -a): 
System ram (free -h): 
chargen@Workstation:/mnt/c/Users/chargen/lrzip-next$ uname -a
Linux Workstation 5.10.102.1-microsoft-standard-WSL2 #1 SMP Wed Mar 2 00:30:59 UTC 2022 x86_64 GNU/Linux
chargen@Workstation:/mnt/c/Users/chargen/lrzip-next$ free -h
               total        used        free      shared  buff/cache   available
Mem:            12Gi        90Mi        11Gi       0.0Ki       653Mi        12Gi
Swap:          4.0Gi          0B       4.0Gi
chargen@Workstation:/mnt/c/Users/chargen/lrzip-next$

### Additional Context

chargen@Workstation:/mnt/c/Users/chargen/lrzip-next$ ./autogen.sh
-bash: ./autogen.sh: /bin/env: bad interpreter: No such file or directory
chargen@Workstation:/mnt/c/Users/chargen/lrzip-next$ vim autogen.sh
chargen@Workstation:/mnt/c/Users/chargen/lrzip-next$ which bash
/bin/bash

chargen@Workstation:/mnt/c/Users/chargen/lrzip-next$ autom4te: error: /usr/bin/m4 terminated by signal: 2
 git submodule update --init
Submodule 'lrzip-fe' (https://github.com/pete4abw/lrzip-fe) registered for path 'lrzip-fe'
Cloning into '/mnt/c/Users/chargen/lrzip-next/lrzip-fe'...
Submodule path 'lrzip-fe': checked out '74108d15960900aec42c49b3fe99eec17993f588'
chargen@Workstation:/mnt/c/Users/chargen/lrzip-next$ automake
sh: 1: ./util/gitdesc.sh: not found
sh: 1: ./util/gitdesc.sh: not found
sh: 1: ./util/gitdesc.sh: not found
sh: 1: ./util/gitdesc.sh: not found

also new: configure: error: Could not find gpg-error library - please install libgpg-error-dev

**Comment by pete4abw** [comment]
`#!/bin.env bash` is an error. Actual file has `#!/bin/env bash`.

/bin/env was implemented for MACOS. Using bash directly, or possibly even #!/bin/sh might work.

I've gone back and forth on this. /bin/env works for most. Don't know about WSL though...

gpg libraries are essential and required.
