### ISSUE TITLE
Add bzip3 as a submodule

### ISSUE THREAD

**Issue by kspalaiologos** [pete4abw/lrzip-next#90]
Adding bzip3 as a git submodule (as explained e.g. [here](https://git-scm.com/book/en/v2/Git-Tools-Submodules)) would be a better idea than copying the entire source code to the trunk - it would allow for easier updates and code management.

**Comment by pete4abw** [comment]
> Adding bzip3 as a git submodule (as explained e.g. [here](https://git-scm.com/book/en/v2/Git-Tools-Submodules)) would be a better idea than copying the entire source code to the trunk - it would allow for easier updates and code management.

Yeah, I considered it. Two reasons I did not. 1) this was experimental right now and 2) I only wanted the library code, not the whole source tree since the library is linked in statically. I'll keep it under advisement.
